version: '3.8'

services:
  anovit:
    build:
      context: ..                      # NOCTUA ルートをビルドコンテキストに
      dockerfile: docker/Dockerfile    # Dockerfile の相対パス
    container_name: Noctua            # コンテナ名
    shm_size: '2gb'

    env_file:
      - .env                           # DATASET_PATH を読み込む

    ports:
      - '50000:8888'  # Jupyter Notebook
      - '8097:8097'   # Visdom

    volumes:
      - ../:/workspace                  # NOCTUA 全体を /workspace にマウント
      #- ${DATASET_PATH}:/workspace/data # データセットを /workspace/DataSet にマウント
      - ${DATASET_PATH}/Lung_dataset_original:/workspace

    working_dir: /workspace
    command: bash -c "jupyter notebook --allow-root --ip=0.0.0.0 --port=50000"