version: '3.8'

services:
  anovit:
    build:
      context: ..                     # NOCTUA ルートをビルドコンテキストに
      dockerfile: docker/Dockerfile   # 同じ Dockerfile
      args:
        REQUIREMENTS_FILE: requirements-gpu.txt  # GPU用依存指定
    container_name: Noctua           # コンテナ名
    shm_size: '2gb'

    env_file:
      - .env

    ports:
      - '50000:8888'
      - '8097:8097'

    volumes:
      - ../:/workspace
      - ${DATASET_PATH}:/workspace/data

    working_dir: /workspace/AnoVit
    command: bash -c "jupyter notebook --allow-root --ip=0.0.0.0 --port=50000"

    runtime: nvidia                   # GPU ランタイム
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]